BASICS OF NUMPY

In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
# creating 1d array
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [4]:
# creating 2d array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [82]:
# get dimension
a.ndim

1

In [83]:
# get shape
a.shape

(4,)

In [7]:
# get shapw
b.shape

(2, 3)

In [8]:
# get type
a.dtype

dtype('int16')

In [9]:
a.dtype

dtype('int16')

In [10]:
# get size
a.itemsize

2

In [11]:
b.itemsize

8

In [12]:
a.nbytes

6

In [13]:
b.nbytes

48

Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# get a specific element[r,c]
a[1,1]

np.int64(9)

In [16]:
a[1,-2]

np.int64(13)

In [17]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# get a specific column
a[:,2]

array([ 3, 10])

In [19]:
# getting specific element [startindex:stopindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [20]:
a[1,6] = 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 22]]


In [21]:
a[:,5] = [1,2]
print(a)

[[ 1  2  3  4  5  1  7]
 [ 8  9 10 11 12  2 22]]


In [22]:
a[2,:] = 11
print(a)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [24]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
b.shape

(2, 2, 3)

In [26]:
# get specific element (work outside in)
b[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [27]:
# get specific element (work outside in)
b[0,1,1]

np.int64(5)

In [28]:
# replace
b[:,1,:] = [[9,9,9],[8,8,8]]
print(b)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


In [29]:
b

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

In [30]:
b[:,1,:] = [[9,9,9],[8,8,8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [31]:
b

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

Initializing Different Types of Arrays

In [32]:
# all 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
# all 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [34]:
# any other element 
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [35]:
# any other element(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [36]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# random decimal no
np.random.rand(4,2)

array([[0.12114333, 0.17791671],
       [0.28545689, 0.69385097],
       [0.77969376, 0.66580031],
       [0.36930844, 0.61836902]])

In [38]:
np.random.randint(0,10,5)

array([6, 7, 7, 4, 4], dtype=int32)

In [39]:
np.random.random_sample(a.shape)

array([[0.13060105, 0.72747163, 0.65879893, 0.01650011, 0.70436744,
        0.93999457, 0.89281013],
       [0.18383127, 0.51523764, 0.24713111, 0.02031558, 0.89612991,
        0.00304191, 0.01531123]])

In [ ]:
# [start:stop:size]
np.random.randint(-1,5, size=(3,3))

array([[ 4, -1,  3],
       [ 1,  3,  1],
       [ 1,  2,  4]], dtype=int32)

In [46]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [53]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [62]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])

Mathematics

In [70]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [71]:
a + 2

array([3, 4, 5, 6])

In [72]:
a * 2

array([2, 4, 6, 8])

In [73]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [74]:
a // 2

array([0, 1, 1, 2])

In [75]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [76]:
a / b

C:\Users\HP\AppData\Local\Temp\ipykernel_16188\1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([ 1., inf,  3., inf])

In [77]:
a * b

array([1, 0, 3, 0])

In [78]:
a ** 2

array([ 1,  4,  9, 16])

In [79]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [81]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [93]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# a*b
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0


Statistics