BASICS OF NUMPY

In [1]:
import numpy as np

In [2]:
import numpy as np

In [3]:
# creating 1d array
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [4]:
# creating 2d array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# get dimension
a.ndim

1

In [6]:
# get shape
a.shape

(3,)

In [7]:
# get shapw
b.shape

(2, 3)

In [8]:
# get type
a.dtype

dtype('int16')

In [9]:
a.dtype

dtype('int16')

In [10]:
# get size
a.itemsize

2

In [11]:
b.itemsize

8

In [12]:
a.nbytes

6

In [13]:
b.nbytes

48

In [54]:
# indexing with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

Accessing/Changing specific elements, rows, columns, etc

In [14]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# get a specific element[r,c]
a[1,1]

np.int64(9)

In [16]:
a[1,-2]

np.int64(13)

In [17]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
# get a specific column
a[:,2]

array([ 3, 10])

In [19]:
# getting specific element [startindex:stopindex:stepsize]
a[0, 1:-1:1]

array([2, 3, 4, 5, 6])

In [20]:
a[1,6] = 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 22]]


In [21]:
a[:,5] = [1,2]
print(a)

[[ 1  2  3  4  5  1  7]
 [ 8  9 10 11 12  2 22]]


In [22]:
a[2,:] = 11
print(a)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
b.shape

(2, 2, 3)

In [ ]:
# get specific element (work outside in)
b[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# get specific element (work outside in)
b[0,1,1]

np.int64(5)

In [ ]:
# replace
b[:,1,:] = [[9,9,9],[8,8,8]]
print(b)

[[[1 2 3]
  [9 9 9]]

 [[7 8 9]
  [8 8 8]]]


In [ ]:
b

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

In [ ]:
b[:,1,:] = [[9,9,9],[8,8,8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
b

array([[[1, 2, 3],
        [9, 9, 9]],

       [[7, 8, 9],
        [8, 8, 8]]])

Initializing Different Types of Arrays

In [ ]:
# all 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# all 1's matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# any other element 
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [ ]:
# any other element(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# random decimal no
np.random.rand(4,2)

array([[0.55436633, 0.04366486],
       [0.15725408, 0.83211856],
       [0.98868322, 0.76453113],
       [0.58333047, 0.07268928]])

In [ ]:
np.random.randint(0,10,5)

array([3, 3, 5, 5, 4], dtype=int32)

In [ ]:
np.random.random_sample(a.shape)

array([[0.39333429, 0.91484688, 0.65048282, 0.63146073, 0.48123326,
        0.07930815, 0.01273257],
       [0.06657178, 0.43289825, 0.99701113, 0.22219632, 0.82711812,
        0.29961906, 0.51696309]])

In [ ]:
# [start:stop:size]
np.random.randint(-1,5, size=(3,3))

array([[ 0,  1, -1],
       [ 0,  2,  0],
       [ 4,  1,  2]], dtype=int32)

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
# print(output)

z = np.zeros((3,3))
z[1,1] = 9
# print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])

Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a // 2

array([0, 1, 1, 2])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [40]:
a / b

ValueError: operands could not be broadcast together with shapes (2,7) (2,3) 

In [41]:
a * b

ValueError: operands could not be broadcast together with shapes (2,7) (2,3) 

In [ ]:
a ** 2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# take the sin
np.sin(a)

array([[0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [ ]:
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# a*b
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [23]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [29]:
np.max(stats, axis = 1)

array([3, 6])

In [32]:
np.sum(stats, axis = 0)

array([5, 7, 9])

Reorganizing Array

In [36]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
# horizontal stacking
h1 = np.ones((4,2))
h2 = np.zeros((4,2))

np.hstack([h1,h2])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

Miscellaneous

Load Data from File

In [48]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
# print(filedata.astype('int32'))
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing

In [50]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [55]:
np.any(filedata > 50, axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [56]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [58]:
(~((filedata > 50) & (filedata < 100)))


array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])